apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: tuxedo-msgsvc
  namespace: NAMESPACE_PLACEHOLDER
  labels:
    app: tuxedo-msgsvc
    app.kubernetes.io/component: tuxedo
    app.kubernetes.io/part-of: tuxedo-to-camel-demo
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'tuxedo-msgsvc:latest'
  source:
    type: Git
    git:
      uri: 'GIT_REPO_PLACEHOLDER'
      ref: GIT_BRANCH_PLACEHOLDER
    contextDir: components/tuxedo
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Containerfile.c
      from:
        kind: ImageStreamTag
        name: 'tuxedo-base:22.1.1.0.0'
        namespace: NAMESPACE_PLACEHOLDER
  triggers:
    - type: ConfigChange
    - type: ImageChange
