apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: tuxedo-msgsvc
  namespace: demo-tuxedo
  labels:
    app: tuxedo-msgsvc
    app.kubernetes.io/component: tuxedo
    app.kubernetes.io/part-of: tuxedo-to-camel-demo
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'tuxedo-msgsvc:latest'
  source:
    type: Git
    git:
      uri: 'https://github.com/kamorisan/tuxedo-to-camel.git'
      ref: feature/implementation
    contextDir: components/tuxedo
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Containerfile
      from:
        kind: ImageStreamTag
        name: 'tuxedo-base:22.1.1.0.0'
        namespace: demo-tuxedo
  triggers:
    - type: ConfigChange
    - type: ImageChange
