# Application
quarkus.application.name=webui
quarkus.http.port=8080

# Tuxedo Client
quarkus.rest-client.tuxedo.url=${TUXEDO_URL:http://tuxedo-msgsvc.demo-tuxedo-c.svc.cluster.local:8080}

# Logging
quarkus.log.console.format=%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n
quarkus.log.level=INFO
quarkus.log.category."com.example".level=DEBUG

# Health
quarkus.smallrye-health.root-path=/health

# CORS (for development)
quarkus.http.cors=true
quarkus.http.cors.origins=*
