apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: example-topic
  namespace: NAMESPACE_PLACEHOLDER
  labels:
    strimzi.io/cluster: KAFKA_CLUSTER_NAME
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
