apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: webui
  namespace: demo-webui
  labels:
    app: webui
    app.kubernetes.io/name: webui
    app.kubernetes.io/component: frontend
spec:
  output:
    to:
      kind: ImageStreamTag
      name: webui:latest
  source:
    type: Binary
    binary: {}
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  triggers: []
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: webui
  namespace: demo-webui
  labels:
    app: webui
    app.kubernetes.io/name: webui
    app.kubernetes.io/component: frontend
spec:
  lookupPolicy:
    local: true
