# Quarkus Configuration
quarkus.application.name=camel-kafka-bridge

# Camel
camel.context.name=camel-kafka-bridge

# AMQP Configuration
quarkus.qpid-jms.url=amqp://amq-broker-hdls-svc.demo-amq.svc.cluster.local:5672
quarkus.qpid-jms.username=
quarkus.qpid-jms.password=

# Kafka Configuration
kafka.brokers=demo-kafka-kafka-bootstrap.demo-kafka.svc.cluster.local:9092

# Logging
quarkus.log.console.enable=true
quarkus.log.console.format=%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n
quarkus.log.level=INFO
quarkus.log.category."com.example".level=INFO

# Health
quarkus.smallrye-health.root-path=/health
