apiVersion: v1
kind: Service
metadata:
  name: camel-kafka-bridge
  namespace: NAMESPACE_PLACEHOLDER
  labels:
    app: camel-kafka-bridge
    app.kubernetes.io/component: camel
    app.kubernetes.io/part-of: tuxedo-to-camel-demo
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: camel-kafka-bridge
  type: ClusterIP
